### ISSUE TITLE
Access Key not set correctly in travis config file

### ISSUE THREAD

**Issue by xicheng87** [xylucien/MusicalKits_Converter#4]
https://github.com/lucien386/MusicXML2ABCNotationWebApp/blob/b941055c4e278a549c27400d4f5e5640a3e8a541/.travis.yml#L16

This line does not appear correct according to this tutorial: 

https://camillovisini.com/flask-deployment-aws-elastic-beanstalk-travis-ci/

Specifically, 

```
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_ACCESS_KEY_SECRET
  region: $AWS_REGION
  app: $AWS_EB_APPLICATION
  env: $AWS_EB_ENVIRONMENT
  bucket_name: $AWS_EB_S3_BUCKET
```
Where the environmental variables all start with a `$`, and can be set by travis:

`travis encrypt --pro AWS_ACCESS_KEY_ID="YOUR_KEY_ID_HERE" --add`

See the second last section right before "conclusion" of the referenced tutorial above and see you can fix this.
